name: Build & Test
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore -f ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Install test dependencies
      run: dotnet restore
    - name: Build Tests
      run: dotnet build --configuration Release --no-restore
    - name: Check ELFs
      run: find ImpromptuNinjas.ZStd/runtimes -name libzstd.so -print -exec readelf -hW {} \; -exec echo \;
    - name: Check DLLs
      run: find ImpromptuNinjas.ZStd/runtimes -name libzstd.dll -exec objdump -wf {} \;
    - name: Test
      run: dotnet test --configuration Release --no-restore --no-build