name: Build & Test
on:
  push:
    branches: [ '*' ]
  pull_request:
    branches: [ master ]
jobs:
  build-and-test-ubuntu:
    runs-on: ubuntu-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore -f ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Test NET Core v3.1 (With RID, 64-bit)
      run: dotnet test --configuration Release -p:RuntimeIdentifier=linux-x64 ImpromptuNinjas.ZStd.Tests/ImpromptuNinjas.ZStd.Tests.NetCore31.csproj
    - name: Build Tests (No RID)
      run: dotnet build --configuration Release
    - name: Check ELFs
      run: find ImpromptuNinjas.ZStd/runtimes -name libzstd.so -print -exec readelf -hW {} \; -exec echo \;
    - name: Check DLLs
      run: find ImpromptuNinjas.ZStd/runtimes -name libzstd.dll -exec objdump -wf {} \;
    - name: Test NET Core v3.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/ImpromptuNinjas.ZStd.Tests.NetCore31.csproj
    - name: Test NET Standard v1.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard11/ImpromptuNinjas.ZStd.Tests.NetStandard11.csproj
    - name: Test NET Standard v1.4
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard14/ImpromptuNinjas.ZStd.Tests.NetStandard14.csproj
    - name: Test NET Standard v2.0
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard20/ImpromptuNinjas.ZStd.Tests.NetStandard20.csproj
    - name: Test NET Standard v2.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard21/ImpromptuNinjas.ZStd.Tests.NetStandard21.csproj

  build-and-test-win64:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore -f ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Test NET Core v3.1 (With RID, 64-bit)
      run: dotnet test --configuration Release -p:RuntimeIdentifier=win-x64 ImpromptuNinjas.ZStd.Tests/ImpromptuNinjas.ZStd.Tests.NetCore31.csproj
    - name: Test NET Core v3.1 (With RID, 32-bit)
      run: dotnet test --configuration Release -p:RuntimeIdentifier=win-x86 ImpromptuNinjas.ZStd.Tests/ImpromptuNinjas.ZStd.Tests.NetCore31.csproj
    - name: Build Tests (No RID)
      run: dotnet build --configuration Release
    - name: Test NET Core v3.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/ImpromptuNinjas.ZStd.Tests.NetCore31.csproj
    - name: Test NET Standard v1.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard11/ImpromptuNinjas.ZStd.Tests.NetStandard11.csproj
    - name: Test NET Standard v1.4
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard14/ImpromptuNinjas.ZStd.Tests.NetStandard14.csproj
    - name: Test NET Standard v2.0
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard20/ImpromptuNinjas.ZStd.Tests.NetStandard20.csproj
    - name: Test NET Standard v2.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard21/ImpromptuNinjas.ZStd.Tests.NetStandard21.csproj

    - name: Test NET Framework v4.5
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetFramework45AnyCpu/ImpromptuNinjas.ZStd.Tests.NetFramework45AnyCpu.csproj
    - name: Test NET Framework v4.5 x86
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetFramework45x86/ImpromptuNinjas.ZStd.Tests.NetFramework45x86.csproj
    - name: Test NET Framework v4.5 x64
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetFramework45x64/ImpromptuNinjas.ZStd.Tests.NetFramework45x64.csproj


  build-and-test-macos:
    runs-on: macos-latest
    env:
      DOTNET_NOLOGO: 1
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    steps:
    - uses: actions/checkout@v2
      with:
        lfs: true
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.300
    - name: Install dependencies
      run: dotnet restore -f ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Build
      run: dotnet build --configuration Release --no-restore ImpromptuNinjas.ZStd/ImpromptuNinjas.ZStd.csproj
    - name: Test NET Core v3.1 (With RID, 64-bit)
      run: dotnet test --configuration Release -p:RuntimeIdentifier=osx-x64 ImpromptuNinjas.ZStd.Tests/ImpromptuNinjas.ZStd.Tests.NetCore31.csproj
    - name: Build Tests (No RID)
      run: dotnet build --configuration Release
    - name: Check DLLs
      run: find ImpromptuNinjas.ZStd/runtimes -name libzstd.dll -exec objdump -wf {} \;
    - name: Check DyLibs
      run: find ImpromptuNinjas.ZStd/runtimes -name libzstd.dylib -exec objdump -wf {} \;
    - name: Test NET Core v3.1
      run: dotnet test --configuration Release --no-restore ImpromptuNinjas.ZStd.Tests/ImpromptuNinjas.ZStd.Tests.NetCore31.csproj
    - name: Test NET Standard v1.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard11/ImpromptuNinjas.ZStd.Tests.NetStandard11.csproj
    - name: Test NET Standard v1.4
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard14/ImpromptuNinjas.ZStd.Tests.NetStandard14.csproj
    - name: Test NET Standard v2.0
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard20/ImpromptuNinjas.ZStd.Tests.NetStandard20.csproj
    - name: Test NET Standard v2.1
      run: dotnet test --configuration Release --no-restore --no-build ImpromptuNinjas.ZStd.Tests/NetStandard21/ImpromptuNinjas.ZStd.Tests.NetStandard21.csproj
